mer-hybris/hybris-boot

- fixup-mountpoints
Change-Id: I7c29f6ffe4176c6525fa51ba20250ab9887420ef
> Set mountpoints for flo

- fixup-mountpoints
Change-Id: Id164bec1e82871d1eeb526ae1a7e8f7565208fef
> Added config for samsung n7100

- fixup-mountpoints
> config for Sony Xperia Z, aka yuga

- fixup-mountpoints
This time with nice prefix right from the beginning :)
> [yuga] adapt path of block devices for usage with systemd

- init-script
This fixes halting to debug mode in init by changing the conditionals.
> Fix conditionals for debugging.

- fixup-mountpoints
Change-Id: I4b5b2f594b9852a1a166f38cbe41e8eeb9acf92c
> [kis3] add ZTE Open C to fixup-mountpoints

- fixup-mountpoints
Add all remaining 2011 Sony Ericsson Xperia devices to fixup-mountpoints.
> [2011xperia] Add all remaining 2011 Xperias to fixup-mountpoints.

- fixup-mountpoints
Need to include additional partitions for sony z3c/aries in the fixup-mountpoints script.
> Fixup mountpoints z3c

- fixup-mountpoints
Signed-off-by: Chris Leach <cxl000@hotmail.com>
deb and flo have same partition layout.
Add deb and additional partitions mentioned in fstab/init files
> [deb/flo] Add deb partitions

- Android.mk
- fixup-mountpoints
Made a mess on the old PR, just reforked.
> hybris-hal building for Android M

- fixup-mountpoints
> [onyx] Added Mountpoints

- Android.mk
- assert-device
- updater-script
should fix possibly flash error (http://bit.ly/1GVWppT)
Change-Id: I567623328b28a96dca6b3208857f19e3dc09a1a3
please close #70
> [updater] use ota device name stored in BoardConfig.mk

- fixup-mountpoints
It's time to add the Oppo find5
> [find5] add Oppo Find 5 to fixup-mountpoints

- init-script
`touch /init_disable_telnet` from within the Sailfish OS rootfs
> Provide possibility to disable telnet

- fixup-mountpoints
Change-Id: I42de9e9d5247c87d5066dde443f42a02c90a09db
Signed-off-by: Zhang Xingtao <xingtao.zhang@yahoo.com>
> [gemini] add Xiaomi Mi5 to fixup-mountpoints

- fixup-mountpoints
Signed-off-by: Viktor Oreshkin <stek29@users.noreply.github.com>
> Fixup-mountpoints for kenzo

- Android.mk
To keep the system building, a merge will be needed here too: https://github.com/mer-hybris/droid-hal-device/pull/164
> Make hybris-boot submodule friendly

- fixup-mountpoints
For reference, here is the output of `ls -l` executed in `/dev/block/bootdevice/by-name`: https://pastebin.com/2hZq8MB1
> [oneplus3] Update fixup-mountpoints

- fixup-mountpoints
Change-Id: I39299f95ebedb2e9a18b80dc65c6af1cad0c94d6
> [addison] Add Moto Z Play to fixup-mountpoints

- fixup-mountpoints
Change-Id: I7c215d4507bcb76a2794668cddd4edf0b534232b
> [mido] Add Redmi Note 4 to fixup-mountpoints

- fixup-mountpoints
[cheesburger] Add mountpoints fixup for OnePlus 5
> Adds mountpoints for OnePlus 5 (cheeseburger)

- fixup-mountpoints
> it will cause the compilation to fail.

- init-script
Fix #139 (#140)
Change-Id: I1ac21721bc1f018d37f0952a0b968ca0d8c1972e
Signed-off-by: Kay <i@v2bv.net>
> [init-script] Check /sys/class/android_usb/android0 to determine which mode is going to be used

- Android.mk
* if HYBRIS_BOOT_PART is missing simply skip hybris-updater-script instead of failing.
* some devices use subfolders (so we have to find fstabs inside them)
> [hybris-boot] Be more flexible with HYBRIS_BOOT_PART and fstabs. JB#42816

- fixup-mountpoints
Adding mount points for Sony Xperia XZ2
> [akari] Add Sony Xperia XZ2 to fixup-mountpoints

- Android.mk
[hybris-boot] provide battery capacity from hw adaptation to sfos. JB#48187
> hybris-boot: provide battery capacity from hw adaptation to sfos

- fixup-mountpoints
Change-Id: Ief2c557c7ed56a60c7816c97fbee28276a7da8f7
> Add Google Pixel 2 / 2 XL to fixup-mountpoints

- fixup-mountpoints
Change-Id: I9dfcb7719a4887e2f8385144117b341de5480703
> [FP3] Add Fairphone 3 to fixup-mountpoints

- fixup-mountpoints
[griffin] Add Xperia 1 fixup-mountpoints
> [kumano] Add Xperia 1 and 5 to fixup-mountpoints

- Android.mk
- fixup-mountpoints
- init-script
Support for lz4 compressed ramdisks. Add fixup-mountpoint entries for some devices.
> Android 13 support

- Android.mk
- init-script
Build vendor_boot image when needed.
> [hybris-boot] Add support for loading modules
