Android.mk

Fixes infinite loop when fstab is not found. This happens for example for devices with fstab file(s) in an extra device repo instead of the main device repo. To improve finding fstab files search for the files also in other device repos of same vendor if fstab files were not found in primary device repo.

Fix infinite loop when fstab is not found. Improve finding fstab files.

---

Android.mk

When doing image creation in OBS or mic, the default image creation
tools from droid-hal-tools package don't always work if the device
requires special version of those tools.
Let's build all the tools: img2simg, simg2img, and mkbootimg always
with hybris-hal, so they can easily be packaked in droid-hal-device
to a separate device specific tools package. Please note mkbootimg
is already required by hybris-boot, so no special dependency was
added for it.
Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

[tools] Build img2simg_host and simg2img_host for hybris-hal 

---

Android.mk

This reverts commit cde067a1d613a88209b1ecf8c955019425e16315.
If one needs OBS packaged special version of droid-hal-tools,
the correct way is to branch a version of droid-hal-tools
and modify it to build the correct version of tools.
Signed-off-by: Kalle Jokiniemi <kalle.jokiniemi@jolla.com>

Revert "[tools] Build img2simg_host and simg2img_host for hybris-hal"

---

init-script

Copying earlier version of hybris-boot/init-script as rootfs /init-debug would have resulted in halted boot (stuck before UI) for every SFE device (and would require telnet and echo continue for every boot). This is the reason previous equivalent dhd's PR was never merged, nor SFE device could switch to modular layout (where init-script is already being copied over)
This PR fixes it, providing mechanism to halt (in inject loop) only when user wants so (by touch /init_enter_debug2)
After merging this, SFE devices can safely switch to modular packaging layout.

Don't halt in post-switch_root

---

Android.mk

because it relies on the OpenGL TLS slot
libhybris glesv1 implementation also has to be changed (TODO) to load the correct version of libGLESv1_CM.so
Change-Id: Ic1d9130f4e2edd187ed9fd1aa15db4391f2be074

libGLESv1_CM also needs to be built by hybris-hal

---

init-script

Using -b switch for telnetd instead of -p, so we can specify an ip address (in addition to port) to listen on. If using only -p telnetd will listen on all interfaces.

Don't allow telnet from outside of USB network

---

init-script

Some devices have both usb0 and rndis0 interfaces and enabling them both with the same IP address will cause USB networking to fail. Current experience tells that rndis0 should be preferred in this situation so let's make usb0 interface initialized only if rndis0 initialization fails.

Fix USB networking on devices with both usb0 and rndis0 interfaces.

---

updater-script
updater-unpack.sh

Extracting filesystem tarball can fail for various reasons
(e.g. no space left on /data partition). Check that extracting
files was successful or abort installation otherwise.

[updater] check that filesystem is extracted successfully

---

fixup-mountpoints

This patch is for devices with the new partition layout (released for MIUI MM)

[cancro] add Xiaomi Mi3 to fixup-mountpoints

---

fixup-mountpoints

The same approach should work for other revisions: jena & trebon but untested.

[jenad] Add Samsung Galaxy Mini 2 to fixup-mountpoints

---

fixup-mountpoints

i9100g uses the same processor as galaxy tab 2 (omap4430) so the mountpoints are the same
take note that i9100g (omap based) is different from i9100 (exynos based)
Change-Id: I67c0240d31e68b131d98b00ff6d899c113fdeef7

[i9100g] Add Samsung Galaxy S2 G to fixup mountpoints

---

Android.mk

Since Frankenstein builds are becoming more popular we need to build both 32bit and 64bit libs, this lays the ground work for that.
If you attempt `make libc` it'll build whichever is the preferred version, so if its a 64bit target arch, force it to build 32bit as well.

[arm64] force build of 32bit binaries if target arch is arm64

---

fixup-mountpoints

Z3 Compact has kernel unified with Z2, therefore mountpoints are the same. Should be same for Z3 and Z2 Tablet as well, as they are all shinano.

[sirius] add detection to fixup-mountpoints

---

Android.mk
fixup-mountpoints
init-script

Add support for configfs based devices, add support for android 8, add pioneer to fixup-mountpoints.
NOTE(configfs): based on @cxl000's patch, but since some devices use rndis_bam.rndis instead of rndis.usb0 this was accounted for.
NOTE(Android 8): build/ needs a different patch now. This patch is both required to minimize the build AND to make sure everything we need is actually built. The patch in build makes use of HYBRIS_TARGETS.
Due to Android 8 changes we also need to be more explicit about what we need.
NOTE(pioneer): this is the initial mountpoint information, other repositories are being prepared right now.

Add support for configfs based devices, add support for android 8, add pioneer to fixup-mountpoints.

---

Android.mk

Needed for marking boot as successful as kernel flashing on Android 8 devices.

[hybris-boot] Build bootctl for Android 8. MER#1947

---

fixup-mountpoints

Needed for builds based on hybris-sony-aosp-8.1.0_r35_20180714 manifest. References https://github.com/sonyxperiadev/device-sony-nile/commit/63e997bd3a8b8f238c72ebe06a307eb8885507a6#diff-40daccd8cf511233914df004c1f9c3cc and https://github.com/mer-hybris/device-sony-nile/pull/1

[pioneer] Adapt pioneer mountpoints to upstream changes. MER#1948

---

Android.mk

If a device needs libsf_compat_layer targets built, it will need to have an
Android.mk packaged in a separate repository, similarly like droidmedia does.

No longer build libsf_compat_layer targets

---

Android.mk

Some adaptations require it during the build.

[hybris-boot] make fec since Android 8

---

Android.mk

In android 9, PLATFORM_VERSION is 9, there is no minor component.  This
causes the test command to fail, and therfore the wrong SET_PERMISSIONS
command is set.

[hybris-boot] Set ANDROID_VERSION_MINOR to 0 if not set. MER#2049

---

fixup-mountpoints

Initial mountpoints for this device on `14.1` were added by @xreactx in the beginning of 2018: https://github.com/mer-hybris/hybris-boot/pull/120
[Treble support & /vendor partition was added by OnePlus for the phone in OxygenOS Oreo 5.1.6](https://forums.oneplus.com/threads/oxygenos-5-1-6-5-1-7-hotfix-ota-for-the-oneplus-5-5t.929455/)
[List of new partitions after the OTA is applied applied (from 5.1.5)](https://pastebin.com/i2B84kz5)
Quite literally everyone has updated past OOS 5.1.6 which released back in October 2018, the old 14.1 based port hasn't seen the light of day and my 15.1 based port has pretty much everything except call audio working right now.
[Preview pictures of the port can be found here](https://imgur.com/a/Bq3yH4q)
I'd appreciate it very much if you merge this PR, …

[cheeseburger] Update fixup-mountpoints

---

Android.mk

Safe to use for local hadk builds, and will not inflate OBS builds as hybris-hal stays the same.

targets for droidmedia and audioflingerglue

---

Android.mk

Android 10 doesn't allow the use of external tools and since mkbootimg
is already used inside AOSP, just resuse the rules from AOSP.
Fixes errors like: "build/make/core/Makefile:1944: error: real file "out/target/product/griffin/boot.img" depends on PHONY target "mkbootimg""

[hybris-boot] Reuse mkbootimg

---

Android.mk

Starting with Android 10 init is split up in two[1][2][3]: second and late
stage init, with one for vendor and one for system init.
[1] https://android.googlesource.com/platform/system/core/+/31438489c0e263ca39f7ba77fe4e50334f2efab7
[2] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.bp#156
[3] https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r6/init/Android.mk#60
Depends on #173

[hybris-boot]  Build only init_second_stage for Android 10+

---

fixup-mountpoints

Added required mountpoints for the OnePlus 6 / enchilada

OnePlus 6/6T: Add to fixup-mountpoints

---

Android.mk

Not all devices even with Android >= 7 provide custom power_profile.xml

[hybris-boot] Don't abort build if battery capacity isn't provided
